

title: "Dokus Theme"
#theme: "hugo-cidb-dokus"

# aufbau /docs/COLLECTION/SPACES/VERSION/
collection: true
spaces: true

params:
  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false
