

title: "Dokus Theme"

#theme: "hugo-cidb-dokus"

# aufbau /doc/COLLECTION/SPACES/VERSION/
collection: true
spaces: true



params:
  doc:
    collapsible: true

  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false



cascade:
  - _target:
      path: "/doc/_index.md"
    type: doc    
  - _target:
      path: "/spaces/*/doc/_index.md"
    type: doc    

  - _target:
      path: "/doc/**"
      kind: Page
    type: doc/page
  - _target:
      path: "/spaces/*/doc/**"
      kind: Page
    type: doc/page


  - _target:
      path: "**/doc/*/**"
      kind: Section
    type: doc/page


