## NEED TO IMORT START

params:
  searchengine: pagefind #fuse, pagefind

## Language
defaultContentLanguage: de
languages:
  de:
    title: Doku Theme
    description: Docs
    languageName: Germany
    weight: 1

module:
  mounts:
    - source: content/de
      target: content


outputs:
  section: [HTML, RSS, PRINT, FUSE_SEARCH]  # FUSE_SEARCH_DOC,PRINT
  page: [HTML]   
  home:
    - HTML
    - RSS
    - FUSE_SEARCH
  #  - DOCPATHS

languages:
  de:
    title: Doku Theme
    description: Docs
    languageName: Germany
    weight: 1


params:
  searchengine: pagefind #fuse, pagefind
  doc:
    collapsible: true
  page:
  top:
    enable: true
    fluid: false
  nav:
    enable: true
    fluid: false

outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print    
    permalinkable: false
  fuse_search:
    baseName: _searchindex 
    isHTML: false
    mediaType: application/json
    permalinkable: false  