

title: "Dokus Theme"
#theme: "hugo-cidb-dokus"

# aufbau /docs/COLLECTION/SPACES/VERSION/
collection: true
spaces: true



params:
  docs:
    collapsible: true

  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false

cascade:
  - _target:
      path: "**/docs/_index.md"
    type: docs    

  - _target:
      path: "**/docs/**"
      kind: Page
    type: docs/doc

  - _target:
      path: "**/docs/*/**"
      kind: Section
    type: docs/doc




