

title: "Dokus Theme"

#theme: "hugo-cidb-dokus"

# aufbau /doc/COLLECTION/SPACES/VERSION/
collection: true
spaces: true



params:
  doc:
    collapsible: true

  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false


## need to add in

outputs:
  section: [HTML, RSS,JSON, print]   
  page: [HTML, print]   
  home:
    - HTML
    - RSS
    - JSON
    - print
    #- HTMLPDF


outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print
    permalinkable: false

cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single
  - _target:
      path: "**/v/*/**"
    type: doc
    layout: single

  - _target:
      path: "**/v/*"
    type: versions
    layout: list




