## NEED TO IMORT START

outputs:
  section: [HTML, RSS, PRINT]  # FUSE_SEARCH_DOC,PRINT
  page: [HTML]   
  home:
    - HTML
    - RSS
  #  - DOCPATHS

cascade:
  - _target:
      path: "**/doc/**"
    type: doc
  - _target:
      path: "**/v/*/**"
    type: doc
  - _target:
      path: "**/docs/*"
    type: docs    
  - _target:
      path: "**/v/*"
    type: versions
    layout: list

## NEED TO IMORT END


params:
  searchengine: pagefind #fuse, pagefind
  doc:
    collapsible: true
  page:
  top:
    enable: true
    fluid: false
  nav:
    enable: true
    fluid: false

outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print    
    permalinkable: false
  fuse_search:
    baseName: _searchindex 
    isHTML: false
    mediaType: application/json
    permalinkable: false  