

title: "Dokus Theme"

#theme: "hugo-cidb-dokus"

# aufbau /doc/COLLECTION/SPACES/VERSION/
collection: true
spaces: true



params:
  doc:
    collapsible: true

  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false


## need to add in

outputs:
  home:
    - HTML
    - RSS
    - JSON


cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single

cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single

