
title: "Dokus Theme"
#baseURL: https://ci-db.github.io/dokus-site/
theme: "../.."

params:
  searchengine: pagefind #fuse, pagefind

## Language
defaultContentLanguage: de
languages:
  de:
    title: Doku Theme
    description: Docs
    languageName: Germany
    weight: 1

module:
  mounts:
    - source: content/de
      target: content

# Menue

menu:
  main:
    - name: Test Seite
      weight: 1000
      url: https://qprocheck.com
      post: <sup><i class="bi bi-box-arrow-up-right"></i></sup>


outputs:
  section: [HTML, RSS, PRINT, FUSE_SEARCH_DOC]   
  page: [HTML]   
  home:
    - HTML
    - RSS
    - JSON
    #- docpaths

## NEED TO IMORT START
cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single  
  - _target:
      path: "**/v/*/**"
    type: doc
    layout: single
  - _target:
      path: "**/v/*"
    type: versions
    layout: list
