
title: "Dokus Theme"
theme: "../.."

params:
  doc:
    collapsible: true

  page:

  top:
    enable: true
    fluid: false

  nav:
    enable: true
    fluid: false

menu:
  main:
    - name: Test Seite
      weight: 1000
      url: https://qprocheck.com
      post: <sup><i class="bi bi-box-arrow-up-right"></i></sup>



defaultContentLanguage: de
languages:
  de:
    title: Doku Theme
    description: Docs
    languageName: Germany
    weight: 1


## need to add in

outputs:
  section: [HTML, RSS, print, searchindex, searchresult]   
  page: [HTML]   
  home:
    - HTML
    - RSS
    - JSON


outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print    
    permalinkable: false
  searchindex:
    baseName: _searchindex 
    isHTML: false
    mediaType: application/json
    permalinkable: false
  searchresult:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _searchresult
    permalinkable: false    

#reserved words!!
cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single
  - _target:
      path: "**/doku/**"
    type: doc
    layout: single    
  - _target:
      path: "**/v/*/**"
    type: doc
    layout: single
  - _target:
      path: "**/v/*"
    type: versions
    layout: list


module:
  mounts:
    - source: content/de
      target: content
