
title: "Dokus Theme"
#baseURL: https://ci-db.github.io/dokus-site/
theme: "../.."



params:
  searchengine: pagefind #fuse, pagefind

## Language
defaultContentLanguage: de
defaultContentLanguageInSubdir: false
contentDir: "content/de"

languages:
  de:
    title: Doku Theme
    description: Dokumente
    languageName: Germany
    weight: 1
  en:
    contentDir: "content/en"
    title: Docu Theme
    description: Docus
    languageName: English
    weight: 1


#module:
#  mounts:
#    - source: content/de
#      target: content    

# Menue

menu:
  main:
    - name: Test Seite
      weight: 1000
      url: https://example.com
      post: <sup><i class="bi bi-box-arrow-up-right"></i></sup>


outputs:
  section: [HTML, RSS, PRINT, FUSE_SEARCH]  # FUSE_SEARCH_DOC,PRINT
  page: [HTML]   
  home:
    - HTML
    - RSS
    - FUSE_SEARCH
  #  - DOCPATHS

params:
  searchengine: fuse #fuse, pagefind
  doc:
    collapsible: true
  page:
  top:
    enable: true
    fluid: false
  nav:
    enable: true
    fluid: false



outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print    
    permalinkable: false
  fuse_search:
    baseName: _searchindex 
    isHTML: false
    mediaType: application/json
    permalinkable: false      